CREATE USER 'bd2'@'localhost' IDENTIFIED BY 'asdasd';
CREATE DATABASE bd2_tours_21;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP ON bd2_tours_21.* TO 'bd2'@'localhost';
FLUSH PRIVILEGES;
